In [3]:
import pandas as pd
import numpy as np
import requests

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

import folium

import warnings
warnings.filterwarnings('ignore')

In [6]:
gbfs_url = "https://gbfs.citibikenyc.com/gbfs/2.3/gbfs.json"
# Fetching GBFS master feed containing links to station information and station status datasets
response = requests.get(gbfs_url)

data = response.json()

print(data.keys())

dict_keys(['data', 'last_updated', 'ttl', 'version'])

In [7]:
data['data']['en']['feeds']

[{'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/gbfs.json', 'name': 'gbfs'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_information.json',
  'name': 'system_information'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/station_information.json',
  'name': 'station_information'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/station_status.json',
  'name': 'station_status'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/free_bike_status.json',
  'name': 'free_bike_status'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_hours.json',
  'name': 'system_hours'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_calendar.json',
  'name': 'system_calendar'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_regions.json',
  'name': 'system_regions'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_pricing_plans.json',
  'name': 'system_pricing_plans'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_alerts.json',
  'name': 'system_alerts'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/gbfs_versions.json',
  'name': 'gbfs_versions'},
 {'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/en/vehicle_types.json',
  'name': 'vehicle_types'}]

In [12]:
system_information_url = "https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_information.json"

system_information = requests.get(system_information_url).json()

system_information

{'data': {'language': 'en',
  'system_id': 'lyft_nyc',
  'start_date': '2013-05-01',
  'name': 'Citi Bike',
  'timezone': 'America/New_York',
  'url': 'http://www.citibikenyc.com',
  'purchase_url': 'https://account.citibikenyc.com/access-plans',
  'operator': 'Lyft'},
 'last_updated': 1778582287,
 'ttl': 60,
 'version': '2.3'}

In [13]:
free_bike_status_url = "https://gbfs.lyft.com/gbfs/2.3/bkn/en/free_bike_status.json"

free_bike_status = requests.get(free_bike_status_url).json()

free_bike_status

{'data': {'bikes': []},
 'last_updated': 1778582348,
 'ttl': 60,
 'version': '2.3'}

In [14]:
system_hours_url = "https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_hours.json"

system_hours = requests.get(system_hours_url).json()

system_hours

{'data': {'rental_hours': []},
 'last_updated': 1778582347,
 'ttl': 60,
 'version': '2.3'}

In [15]:
system_calendar_url = "https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_calendar.json"

system_calendar = requests.get(system_calendar_url).json()

system_calendar

{'data': {'calendars': [{'start_day': 1,
    'end_month': 12,
    'end_day': 31,
    'start_month': 1}]},
 'last_updated': 1778582407,
 'ttl': 60,
 'version': '2.3'}

In [16]:
system_regions_url = "https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_regions.json"

system_regions = requests.get(system_regions_url).json()

system_regions

{'data': {'regions': [{'region_id': '70', 'name': 'JC District'},
   {'region_id': '71', 'name': 'NYC District'},
   {'region_id': '158', 'name': '8D'},
   {'region_id': '185', 'name': 'Bronx'},
   {'region_id': '189', 'name': 'IC HQ'},
   {'region_id': '190', 'name': 'testzone'},
   {'region_id': '311', 'name': 'Hoboken District'}]},
 'last_updated': 1778582407,
 'ttl': 60,
 'version': '2.3'}

In [17]:
system_pricing_plans_url = "https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_pricing_plans.json"

system_pricing_plans = requests.get(system_pricing_plans_url).json()

system_pricing_plans

{'data': {'plans': [{'price': '4.99',
    'per_min_pricing': [{'start': 0, 'rate': 0.41, 'interval': 1}],
    'description': '$4.99 unlock fee, $0.41 per minute.',
    'is_taxable': True,
    'name': 'EBIKE SINGLE RIDE',
    'plan_id': 'EBIKE_SINGLE_RIDE',
    'currency': 'USD'}]},
 'last_updated': 1778582407,
 'ttl': 60,
 'version': '2.3'}

In [18]:
system_alerts_url = "https://gbfs.lyft.com/gbfs/2.3/bkn/en/system_alerts.json"

system_alerts = requests.get(system_alerts_url).json()

system_alerts

{'data': {'alerts': []},
 'last_updated': 1778582407,
 'ttl': 60,
 'version': '2.3'}

In [19]:
gbfs_versions_url = "https://gbfs.lyft.com/gbfs/2.3/bkn/en/gbfs_versions.json"

gbfs_versions = requests.get(gbfs_versions_url).json()

gbfs_versions

{'data': {'versions': [{'version': 'v1.1',
    'url': 'https://gbfs.lyft.com/gbfs/1.1/bkn/gbfs.json'},
   {'version': 'v2.3',
    'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/gbfs.json'}]},
 'last_updated': 1778582407,
 'ttl': 60,
 'version': '2.3'}

In [20]:
vehicle_types_url = "https://gbfs.lyft.com/gbfs/2.3/bkn/en/vehicle_types.json"

vehicle_types = requests.get(vehicle_types_url).json()

vehicle_types

{'data': {'vehicle_types': [{'vehicle_type_id': '1',
    'form_factor': 'bicycle',
    'propulsion_type': 'human'},
   {'vehicle_type_id': '2',
    'max_range_meters': 69201.62,
    'form_factor': 'bicycle',
    'propulsion_type': 'electric_assist'}]},
 'last_updated': 1778582467,
 'ttl': 60,
 'version': '2.3'}

In [25]:
system_information.keys()
system_information['data']

{'language': 'en',
 'system_id': 'lyft_nyc',
 'start_date': '2013-05-01',
 'name': 'Citi Bike',
 'timezone': 'America/New_York',
 'url': 'http://www.citibikenyc.com',
 'purchase_url': 'https://account.citibikenyc.com/access-plans',
 'operator': 'Lyft'}

In [26]:
regions_df = pd.DataFrame(
    system_regions['data']['regions']
)

regions_df.head()

  region_id          name
0        70   JC District
1        71  NYC District
2       158            8D
3       185         Bronx
4       189         IC HQ

In [27]:
free_bike_status.keys()

dict_keys(['data', 'last_updated', 'ttl', 'version'])

In [28]:
free_bike_df = pd.DataFrame(
    free_bike_status['data']['bikes']
)

free_bike_df.head()

Empty DataFrame
Columns: []
Index: []

In [29]:
system_hours.keys()

dict_keys(['data', 'last_updated', 'ttl', 'version'])

In [30]:
system_hours['data']

{'rental_hours': []}

In [31]:
system_calendar.keys()

dict_keys(['data', 'last_updated', 'ttl', 'version'])

In [32]:
system_calendar['data']

{'calendars': [{'start_day': 1,
   'end_month': 12,
   'end_day': 31,
   'start_month': 1}]}

In [33]:
system_regions.keys()

dict_keys(['data', 'last_updated', 'ttl', 'version'])

In [34]:
regions_df = pd.DataFrame(
    system_regions['data']['regions']
)

regions_df.head()

  region_id          name
0        70   JC District
1        71  NYC District
2       158            8D
3       185         Bronx
4       189         IC HQ

In [35]:
system_pricing_plans.keys()

dict_keys(['data', 'last_updated', 'ttl', 'version'])

In [36]:
pricing_df = pd.DataFrame(
    system_pricing_plans['data']['plans']
)

pricing_df.head()

,price,per_min_pricing,description,is_taxable,name,plan_id,currency
0,4.99,"[{'start': 0, 'rate': 0.41, 'interval': 1}]","$4.99 unlock fee, $0.41 per minute.",True,EBIKE SINGLE RIDE,EBIKE_SINGLE_RIDE,USD

In [37]:
system_alerts.keys()

dict_keys(['data', 'last_updated', 'ttl', 'version'])

In [38]:
system_alerts['data']

{'alerts': []}

In [39]:
gbfs_versions.keys()

dict_keys(['data', 'last_updated', 'ttl', 'version'])

In [40]:
gbfs_versions['data']

{'versions': [{'version': 'v1.1',
   'url': 'https://gbfs.lyft.com/gbfs/1.1/bkn/gbfs.json'},
  {'version': 'v2.3', 'url': 'https://gbfs.lyft.com/gbfs/2.3/bkn/gbfs.json'}]}

In [41]:
vehicle_types.keys()

dict_keys(['data', 'last_updated', 'ttl', 'version'])

In [42]:
vehicle_df = pd.DataFrame(
    vehicle_types['data']['vehicle_types']
)

vehicle_df.head()

  vehicle_type_id form_factor  propulsion_type  max_range_meters
0               1     bicycle            human               NaN
1               2     bicycle  electric_assist          69201.62